# https://github.com/keycloak/keycloak-documentation/blob/master/server_installation/topics/operator/keycloak-client-cr.adoc
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kong-client
  namespace: keycloak
  labels:
    app: default
spec:
  realmSelector:
    matchLabels:
      app: default
  client:
    id: "default"
    clientId: default-client-secret
    secret: default-client-secret
