---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: default
  namespace: keycloak
  labels:
    app: default
spec:
  instances: 1
  externalAccess:
    enabled: False
    host: keycloak.kongeelabs.arpa
    tlsTermination: "reencrypt"
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: 'true'
