apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: default
  namespace: keycloak
  labels:
    app: default
spec:
  realm:
    id: "default"
    realm: "default"
    enabled: True
    displayName: "Default Realm"
  instanceSelector:
    matchLabels:
      app: default
