apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-kong-tls
  namespace: kong
spec:
  secretName: kong-tls
  issuerRef:
    name: kongeelabs-ca-issuer
  dnsNames:
  - manager.kong.braincraft.io
  - portal.kong.braincraft.io
  - kong.braincraft.io
  - braincraft.io
