apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bcio-kingpin-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: usrbinkat@braincraft.io
    privateKeySecretRef:
      name: bcio-kingpin-issuer-key
    solvers:
    - dns01:
        cloudDNS:
          project: kingpin-259919
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
