---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kongeelabs-cluster-issuer
  namespace: kong
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kongeelabs-selfsigned-issuer
  namespace: kong
spec:
  selfSigned: {}
