# docker volume create worker1-containerd
# docker volume create control1-containerd
# kind create cluster --config kind/config.yml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kongee
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
    extraMounts:
    # Shared persistent image cache
    - hostPath: /var/lib/docker/volumes/control1-containerd/_data
      containerPath: /var/lib/containerd
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          "service-account-issuer": "kubernetes.default.svc"
          "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
  - role: worker
    image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
    extraMounts:
      # Shared persistent image cache
      - hostPath: /var/lib/docker/volumes/worker1-containerd/_data
        containerPath: /var/lib/containerd
    extraPortMappings:
    - listenAddress: "127.0.0.1"
      protocol: TCP
      containerPort: 80
      hostPort: 80
    - listenAddress: "127.0.0.1"
      protocol: TCP
      containerPort: 443
      hostPort: 443
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress=true"
         #node-labels: "node-role.kubernetes.io/worker=''"
         #node-labels: ["ingress=true","node-role.kubernetes.io/worker=''"]
