---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo.kongeelabs.home.arpa
  namespace: podinfo
spec:
  isCA: false
  duration: 2160h
  renewBefore: 360h
  secretName: podinfo-tls
  commonName: podinfo.kongeelabs.home.arpa
  dnsNames:
  - "podinfo.kongeelabs.home.arpa"
  - "*.podinfo.kongeelabs.home.arpa"
  issuerRef:
    name: certman-selfsigned-issuer
    kind: ClusterIssuer
