apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex.example.com.tls
  namespace: dex
spec:
  secretName: dex-tls
  commonName: dex.kongeelabs.home.arpa
  dnsNames:
  - "dex.kongeelabs.home.arpa"
  - "*.dex.kongeelabs.home.arpa"
  renewBefore: 360h
  duration: 2160h
  isCA: false
  issuerRef:
    name: certman-selfsigned-issuer
    kind: ClusterIssuer
