replicaCount: 1

config:
  issuer: "https://dex.kongeelabs.arpa"
  enablePasswordDB: true
  storage:
    type: memory

ingress:
  enabled: true
  annotations:
    konghq.com/protocols: "https"
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "true"
    kubernetes.io/ingress.class: "kong"
    ingress.kubernetes.io/service-upstream: "true"
  tls:
    - hosts:
        - dex.kongeelabs.arpa
      secretName: dex-tls
  hosts:
    - host: dex.kongeelabs.arpa
      paths:
        - path: /
          pathType: ImplementationSpecific
envFrom:
- secretRef:
    name: "dex-env"
